### ISSUE TITLE
Add filters for device

### ISSUE THREAD

**Issue by zoe-codez** [Digital-Alchemy-TS/type-writer#9]
**Context**

```yaml
  target:
    entity:
      integration: emporia_vue
      device_class: outlet
    device:
      manufacturer: Emporia
      model: VVDN01
      entity:
        integration: emporia_vue
        device_class: outlet
```
